"""add subcontractor_id to materials

Revision ID: 33a2208b2a81
Revises: d9a2f6c1b8e3
Create Date: 2026-05-10 19:41:49.823248

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '33a2208b2a81'
down_revision = 'd9a2f6c1b8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('subcontractor_id', sa.Uuid(), nullable=True))
    op.alter_column('materials', 'status',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               nullable=False)
    op.create_foreign_key(None, 'materials', 'subcontractors', ['subcontractor_id'], ['id'])
    op.drop_constraint(op.f('fk_project_tasks_subcontractor_id_subcontractors'), 'project_tasks', type_='foreignkey')
    op.drop_column('project_tasks', 'subcontractor_status')
    op.drop_column('project_tasks', 'subcontractor_ordered_date')
    op.drop_column('project_tasks', 'subcontractor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tasks', sa.Column('subcontractor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('project_tasks', sa.Column('subcontractor_ordered_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('project_tasks', sa.Column('subcontractor_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_project_tasks_subcontractor_id_subcontractors'), 'project_tasks', 'subcontractors', ['subcontractor_id'], ['id'])
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.alter_column('materials', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('materials', 'subcontractor_id')
    # ### end Alembic commands ###
