"""add project subtasks

Revision ID: 5f377f41d848
Revises: 9587a611a596
Create Date: 2026-05-11 09:05:03.533503

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f377f41d848'
down_revision = '9587a611a596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_subtasks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('subtask_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subtask_description', sa.Text(), nullable=True),
    sa.Column('project_manager_id', sa.Uuid(), nullable=True),
    sa.Column('project_manager_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('draft_engineer_id', sa.Uuid(), nullable=True),
    sa.Column('draft_engineer_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('engineer_id', sa.Uuid(), nullable=True),
    sa.Column('engineer_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_engineer_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_subtasks')
    # ### end Alembic commands ###
