"""Add cascading deletes for projects

Revision ID: 9dffc568fec6
Revises: 33a2208b2a81
Create Date: 2026-05-11 16:32:00.106807

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9dffc568fec6'
down_revision = '33a2208b2a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_project_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('materials_project_id_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_types_project_id_fkey'), 'order_types', type_='foreignkey')
    op.create_foreign_key(None, 'order_types', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_assignments_project_id_fkey'), 'project_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'project_assignments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_milestones_project_id_fkey'), 'project_milestones', type_='foreignkey')
    op.create_foreign_key(None, 'project_milestones', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_project_tasks_parent_task_id_project_tasks'), 'project_tasks', type_='foreignkey')
    op.drop_constraint(op.f('project_tasks_milestone_id_fkey'), 'project_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'project_tasks', 'project_milestones', ['milestone_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_tasks', 'project_tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('time_logs_project_id_fkey'), 'time_logs', type_='foreignkey')
    op.create_foreign_key(None, 'time_logs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.create_foreign_key(op.f('time_logs_project_id_fkey'), 'time_logs', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_tasks', type_='foreignkey')
    op.drop_constraint(None, 'project_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('project_tasks_milestone_id_fkey'), 'project_tasks', 'project_milestones', ['milestone_id'], ['id'])
    op.create_foreign_key(op.f('fk_project_tasks_parent_task_id_project_tasks'), 'project_tasks', 'project_tasks', ['parent_task_id'], ['id'])
    op.drop_constraint(None, 'project_milestones', type_='foreignkey')
    op.create_foreign_key(op.f('project_milestones_project_id_fkey'), 'project_milestones', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('project_assignments_project_id_fkey'), 'project_assignments', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'order_types', type_='foreignkey')
    op.create_foreign_key(op.f('order_types_project_id_fkey'), 'order_types', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_project_id_fkey'), 'materials', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_project_id_fkey'), 'invoices', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
