from app.crud.materials import (
    get_material_statuses,
    get_materials_by_due_date_and_status,
)
from app.crud.project_statuses import (
    create_status_type,
    get_all_status_types,
    get_status_type,
)


from app.crud.users import (
    authenticate,
    create_user,
    create_user_with_employee,
    delete_user_and_employee,
    get_all_users_with_roles,
    get_employee_hours_since,
    get_user_by_email,
    get_user_profile,
    get_users,
    update_employee_role,
    update_user,
    DUMMY_HASH,
)
from app.crud.projects import (
    PROJECT_TAB_COMPLETED,
    PROJECT_TAB_IN_PROGRESS,
    PROJECT_TAB_TO_BE_INVOICED,
    build_project_details,
    build_project_summaries,
    calculate_project_completion_percent,
    count_active_projects,
    count_completed_projects,
    create_default_project_task_structure,
    create_material,
    create_project,
    create_project_milestone,
    create_project_task,
    delete_all_projects,
    delete_material,
    delete_project,
    delete_project_milestone,
    delete_project_task,
    get_all_active_projects,
    get_all_projects,
    get_delayed_projects,
    get_material,
    get_materials_by_project_id,
    get_overdue_projects,
    get_projects_expected_by_date,
    get_project_manager,
    month_bounds,
    prev_month,
    sum_invoices,
    get_or_create_client,
    get_project_by_id,
    get_project_by_job_number,
    get_project_manager,
    get_project_milestone,
    get_project_tab,
    get_project_task,
    get_project_task_management,
    get_projects_by_due_date,
    get_projects_by_status,
    get_projects_by_tab,
    get_tasks,
    is_project_invoiced,
    month_bounds,
    prev_month,
    sum_invoices,
    update_material,
    update_project,
    update_project_milestone,
    update_project_task,
)
from app.crud.users import (
    DUMMY_HASH,
    authenticate,
    create_user,
    create_user_with_employee,
    delete_user_and_employee,
    get_all_users_with_roles,
    get_user_by_email,
    get_user_profile,
    get_users,
    update_employee_role,
    update_user,
)

from app.crud.project_statuses import (
    get_status_type,
    create_status_type,
    get_all_status_types,
)

from app.crud.invoices import (
    get_finished_invoices_since,
    get_expected_invoices_before,
)


from app.crud.subcontractors import (
    get_subcontractors,
    create_subcontractor
)

__all__ = [
    # users
    "authenticate",
    "create_user",
    "create_user_with_employee",
    "delete_user_and_employee",
    "get_all_users_with_roles",
    "get_employee_hours_since",
    "get_user_by_email",
    "get_user_profile",
    "get_users",
    "update_employee_role",
    "update_user",
    "DUMMY_HASH",
    # projects
    "build_project_summaries",
    "count_active_projects",
    "count_completed_projects",
    "get_all_active_projects",
    "get_delayed_projects",
    "get_overdue_projects",
    "get_projects_expected_by_date",
    "get_project_manager",
    "month_bounds",
    "prev_month",
    "sum_invoices",
    "get_or_create_client",
    "create_project",
    "PROJECT_TAB_IN_PROGRESS",
    "PROJECT_TAB_TO_BE_INVOICED",
    "PROJECT_TAB_COMPLETED",
    "get_project_by_job_number",
    "get_project_by_id",
    "get_all_projects",
    "build_project_details",
    "create_default_project_task_structure",
    "get_projects_by_status",
    "get_project_milestone",
    "create_project_milestone",
    "update_project_milestone",
    "delete_project_milestone",
    "get_project_task",
    "create_project_task",
    "update_project_task",
    "get_project_task_management",
    "get_projects_by_tab",
    "calculate_project_completion_percent",
    "is_project_invoiced",
    "get_project_tab",
    "delete_project",
    "delete_all_projects",
    "update_project",
    "get_projects_by_due_date",
    # project statuses
    "get_status_type",
    "create_status_type",
    "get_all_status_types",
    # invoices
    "get_finished_invoices_since",
    "get_expected_invoices_before",
    #tasks
    "get_tasks",
    "delete_project_task",
    #materials,
    "update_material",
    "create_material",
    "get_material",
    "delete_material",
    "get_material_statuses",
    "get_materials_by_project_id",
    "get_materials_by_due_date_and_status"

    # subcontractors
    "get_subcontractors",
    "create_subcontractor"
]
